version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-medical-app-container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: MyStrongP@ssw0rd
      MSSQL_TCP_PORT: 1433
    ports:
      - "14333:1433"
    volumes:
      - ./sql:/sql
    command: >
      bash -c "(/opt/mssql/bin/sqlservr &)
               until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1'; do sleep 1; done
               /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -i /sql/init.sql
               while true; do sleep 1d; done"

  backend:
    build:
      context: ./backend
      args:
        PROFILE: ${PROFILE:-docker-local}
    container_name: backend-medical-app-container
    depends_on:
      - db
    ports:
      - "8089:8080"
    environment:
      PROFILE: ${PROFILE:-docker-local}

  frontend:
    build: ./frontend
    container_name: frontend-medical-app-container
    depends_on:
      - backend
    ports:
      - "4209:4209"
    environment:
      PROFILE: ${PROFILE:-docker-local}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      bash -c "npm run build:$$PROFILE -- --host 0.0.0.0 --port 4209
               while true; do sleep 1d; done"
