IF NOT EXISTS (SELECT * FROM dbo.medical_specializations)
BEGIN
INSERT INTO medical_specializations (label) VALUES
                                                ('Cardiology'),
                                                ('Dermatology'),
                                                ('Gastroenterology'),
                                                ('Endocrinology'),
                                                ('Hematology'),
                                                ('Immunology'),
                                                ('Neurology'),
                                                ('Oncology'),
                                                ('Ophthalmology'),
                                                ('Orthopedics'),
                                                ('Pediatrics'),
                                                ('Psychiatry'),
                                                ('Pulmonology'),
                                                ('Rheumatology'),
                                                ('Urology'),
                                                ('Allergy and Immunology'),
                                                ('Anesthesiology'),
                                                ('Colon and Rectal Surgery'),
                                                ('Critical Care Medicine'),
                                                ('Diagnostic Radiology'),
                                                ('Emergency Medicine'),
                                                ('Family Medicine'),
                                                ('Internal Medicine'),
                                                ('Medical Genetics and Genomics'),
                                                ('Neonatal-Perinatal Medicine'),
                                                ('Nephrology'),
                                                ('Neurological Surgery'),
                                                ('Nuclear Medicine'),
                                                ('Obstetrics and Gynecology'),
                                                ('Oncology-Hematology'),
                                                ('Otolaryngology'),
                                                ('Pathology'),
                                                ('Pediatric Cardiology'),
                                                ('Pediatric Emergency Medicine'),
                                                ('Pediatric Endocrinology'),
                                                ('Pediatric Gastroenterology'),
                                                ('Pediatric Hematology-Oncology'),
                                                ('Pediatric Infectious Diseases'),
                                                ('Pediatric Nephrology'),
                                                ('Pediatric Pulmonology'),
                                                ('Pediatric Rheumatology'),
                                                ('Pediatric Surgery'),
                                                ('Physical Medicine and Rehabilitation'),
                                                ('Plastic Surgery'),
                                                ('Preventive Medicine'),
                                                ('Psychosomatic Medicine'),
                                                ('Public Health and General Preventive Medicine'),
                                                ('Radiation Oncology'),
                                                ('Surgery'),
                                                ('Thoracic Surgery'),
                                                ('Transplant Hepatology'),
                                                ('Urgent Care Medicine'),
                                                ('Vascular Surgery');
END;
