profile: docker-prod

spring:
  datasource:
    url: jdbc:sqlserver://db:1433;databaseName=medicalApp;encrypt=false;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml

cors:
  allowed-origins: http://frontend:4209

upload:
  path: src/main/resources/static/images/avatars
