profile: docker-local

spring:
  datasource:
    url: jdbc:sqlserver://db:1433;databaseName=medicalApp;encrypt=false;
    username: sa
    password: MyStrongP@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

jwt:
  secret: BauBau
  expiration-time: 86400000

cors:
  allowed-origins: http://localhost:4209

default-admin-should-be-created: true
default-admin-email: admin@admin.com
default-admin-password: admin
