profile: docker-local

spring:
  datasource:
    url: jdbc:sqlserver://db:1433;databaseName=medicalApp;encrypt=false;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000

cors:
  allowed-origins: http://localhost:4209
