profile: local

spring:
  datasource:
    url: jdbc:sqlserver://localhost:14333;databaseName=medicalApp;encrypt=false;
    username: sa
    password: MyStrongP@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml

jwt:
  secret: djmmt049@$2bJa9
  expiration-time: 3600000

cors:
  allowed-origins: http://localhost:4200
