profile: docker-prod

spring:
  datasource:
    url: jdbc:sqlserver://db:${DB_PORT};databaseName=${DB_NAME};encrypt=false;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000

cors:
  allowed-origins: http://frontend:4209

default-admin-should-be-created: true
default-admin-email: ${APP_ADMIN_EMAIL}
default-admin-password: ${APP_ADMIN_PASSWORD}

