name: Angular Checks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  angular-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm run ng test -- --no-watch --no-progress --watch=false --code-coverage --browsers=ChromeHeadless
