name: Combined Build Checks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create Database Image
        run: docker-compose up -d --force-recreate db

      - name: Create Backend Image
        run: docker-compose up -d --force-recreate backend

      - name: Create Frontend Image
        run: docker-compose up -d --force-recreate frontend

  maven-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create Database Image
        run: docker-compose up -d --force-recreate db

      - name: Build and package backend
        working-directory: ./backend
        run: mvn clean install
