name: Docker Checks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ develop, main ]

env:
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  APP_ADMIN_EMAIL: ${{ secrets.APP_ADMIN_EMAIL }}
  APP_ADMIN_PASSWORD: ${{ secrets.APP_ADMIN_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create Database Image
        run: docker-compose up -d --force-recreate db
        env:
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}


      - name: Create Backend Image
        run: docker-compose up -d --force-recreate backend
        env:
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}

      - name: Create Frontend Image
        run: docker-compose up -d --force-recreate frontend
        env:
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
